name: Code Coverage for jvcli

on:
  pull_request:
    paths:
      - "./**"
  push:
    branches:
      - main
    paths:
      - "./**"
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install .[dev]

      - name: Generate Coverage
        run: pytest --cov=jvcli --cov-report=xml

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            thresholdAll: 0.5